[package]
name = "unko"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
dirs = "6.0.0"
fs = "0.0.5"
git2 = "0.20.2"
indicatif = "0.18.0"
once_cell = "1.21.3"
regex = "1.11.1"
rustyline = "16.0.0"
shell-words = "1"
shlex = "1.3.0"
