[package]
name = "unko"
version = "0.1.0"
edition = "2024"

[dependencies]
ansi_term = "0.12.1"
dirs = "6.0.0"
fs = "0.0.5"
git2 = "0.20.2"
libc = "0.2.174"
once_cell = "1.21.3"
rayon = "1.10.0"
rustyline = "16.0.0"
